<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class InstallCitiesCommand extends Command
{
  protected $signature = 'install:cities';


  protected $description = 'Установка городов';

  public function handle(): void
  {
    $this->installCities();
    $this->info('Установка городов...');
  }

  private function installCities(): void
  {
    $cities = [
      ['id' => 1, 'region_id' => 1, 'title' => ['uz' => 'Oxunboboyev', 'ru' => 'Ахунбабаев']],
      ['id' => 2, 'region_id' => 1, 'title' => ['uz' => 'Andijon', 'ru' => 'Андижан']],
      ['id' => 3, 'region_id' => 1, 'title' => ['uz' => 'Asaka', 'ru' => 'Асака']],
      ['id' => 4, 'region_id' => 1, 'title' => ['uz' => 'Xonobod', 'ru' => 'Ханабад']],
      ['id' => 5, 'region_id' => 1, 'title' => ['uz' => 'Xo\'jaobod', 'ru' => 'Ходжаабад']],
      ['id' => 6, 'region_id' => 1, 'title' => ['uz' => 'Qoʻrgʻontepa', 'ru' => 'Кургантепа']],
      ['id' => 7, 'region_id' => 1, 'title' => ['uz' => 'Paxtaobod', 'ru' => 'Пахтаабад']],
      ['id' => 8, 'region_id' => 1, 'title' => ['uz' => 'Poytug\'', 'ru' => 'Пайтуг']],
      ['id' => 9, 'region_id' => 1, 'title' => ['uz' => 'Shahrixon', 'ru' => 'Шахрихан']],
      ['id' => 10, 'region_id' => 2, 'title' => ['uz' => 'Olot', 'ru' => 'Алат']],
      ['id' => 11, 'region_id' => 2, 'title' => ['uz' => 'Buxoro', 'ru' => 'Бухара']],
      ['id' => 12, 'region_id' => 2, 'title' => ['uz' => 'Galaosiyo', 'ru' => 'Галаасия']],
      ['id' => 13, 'region_id' => 2, 'title' => ['uz' => 'Gazli', 'ru' => 'Газли']],
      ['id' => 14, 'region_id' => 2, 'title' => ['uz' => 'G‘ijduvon', 'ru' => 'Гиждуван']],
      ['id' => 15, 'region_id' => 2, 'title' => ['uz' => 'Kogon', 'ru' => 'Каган']],
      ['id' => 16, 'region_id' => 2, 'title' => ['uz' => 'Qorako\'l', 'ru' => 'Каракуль']],
      ['id' => 17, 'region_id' => 2, 'title' => ['uz' => 'Romitan', 'ru' => 'Ромитан']],
      ['id' => 18, 'region_id' => 2, 'title' => ['uz' => 'Shofirkon', 'ru' => 'Шафиркан']],
      ['id' => 19, 'region_id' => 2, 'title' => ['uz' => 'Vobkent', 'ru' => 'Вабкент']],
      ['id' => 20, 'region_id' => 3, 'title' => ['uz' => 'Dashtobod', 'ru' => 'Даштобод']],
      ['id' => 21, 'region_id' => 3, 'title' => ['uz' => 'Do\'stlik', 'ru' => 'Дустлик']],
      ['id' => 22, 'region_id' => 3, 'title' => ['uz' => 'Jizzax', 'ru' => 'Джизак']],
      ['id' => 23, 'region_id' => 3, 'title' => ['uz' => 'Gagarin', 'ru' => 'Гагарин']],
      ['id' => 24, 'region_id' => 3, 'title' => ['uz' => 'G\'allaorol', 'ru' => 'Галляарал']],
      ['id' => 25, 'region_id' => 3, 'title' => ['uz' => 'Marjonbuloq', 'ru' => 'Марджанбулак']],
      ['id' => 26, 'region_id' => 3, 'title' => ['uz' => 'Paxtakor', 'ru' => 'Пахтакор']],
      ['id' => 27, 'region_id' => 4, 'title' => ['uz' => 'Beruniy', 'ru' => 'Беруни']],
      ['id' => 28, 'region_id' => 4, 'title' => ['uz' => 'Bo\'ston', 'ru' => 'Бустан']],
      ['id' => 29, 'region_id' => 4, 'title' => ['uz' => 'Chimboy', 'ru' => 'Чимбай']],
      ['id' => 30, 'region_id' => 4, 'title' => ['uz' => 'Xo\'jayli', 'ru' => 'Ходжейли']],
      ['id' => 31, 'region_id' => 4, 'title' => ['uz' => 'Qo\'ng\'irot', 'ru' => 'Кунград']],
      ['id' => 32, 'region_id' => 4, 'title' => ['uz' => 'Mang\'it', 'ru' => 'Мангит']],
      ['id' => 33, 'region_id' => 4, 'title' => ['uz' => 'Mo\'ynoq', 'ru' => 'Муйнак']],
      ['id' => 34, 'region_id' => 4, 'title' => ['uz' => 'Nukus', 'ru' => 'Нукус']],
      ['id' => 35, 'region_id' => 4, 'title' => ['uz' => 'Shumanay', 'ru' => 'Шуманай']],
      ['id' => 36, 'region_id' => 4, 'title' => ['uz' => 'Taxiatosh', 'ru' => 'Тахиаташ']],
      ['id' => 37, 'region_id' => 4, 'title' => ['uz' => 'To\'rtko\'l', 'ru' => 'Турткуль']],
      ['id' => 38, 'region_id' => 5, 'title' => ['uz' => 'Beshkent', 'ru' => 'Бешкент']],
      ['id' => 39, 'region_id' => 5, 'title' => ['uz' => 'Chiroqchi', 'ru' => 'Чиракчи']],
      ['id' => 40, 'region_id' => 5, 'title' => ['uz' => 'Dehqonobod', 'ru' => 'Дехканабад']],
      ['id' => 41, 'region_id' => 5, 'title' => ['uz' => 'G\'uzor', 'ru' => 'Гузар']],
      ['id' => 42, 'region_id' => 5, 'title' => ['uz' => 'Qamashi', 'ru' => 'Камаши']],
      ['id' => 43, 'region_id' => 5, 'title' => ['uz' => 'Qarshi', 'ru' => 'Карши']],
      ['id' => 44, 'region_id' => 5, 'title' => ['uz' => 'Koson', 'ru' => 'Касан']],
      ['id' => 45, 'region_id' => 5, 'title' => ['uz' => 'Kasbi', 'ru' => 'Касби']],
      ['id' => 46, 'region_id' => 5, 'title' => ['uz' => 'Kitob', 'ru' => 'Китаб']],
      ['id' => 47, 'region_id' => 5, 'title' => ['uz' => 'Mirishkor', 'ru' => 'Миришкор']],
      ['id' => 48, 'region_id' => 5, 'title' => ['uz' => 'Muborak', 'ru' => 'Мубарак']],
      ['id' => 49, 'region_id' => 5, 'title' => ['uz' => 'Nishon', 'ru' => 'Нишан']],
      ['id' => 50, 'region_id' => 5, 'title' => ['uz' => 'Shahrisabz', 'ru' => 'Шахрисабз']],
      ['id' => 51, 'region_id' => 5, 'title' => ['uz' => 'Tolimarjon', 'ru' => 'Талимарджан']],
      ['id' => 52, 'region_id' => 5, 'title' => ['uz' => 'Yakkabog\'', 'ru' => 'Яккабаг']],
      ['id' => 53, 'region_id' => 6, 'title' => ['uz' => 'Qiziltepa', 'ru' => 'Кызылтепа']],
      ['id' => 54, 'region_id' => 6, 'title' => ['uz' => 'Navoiy', 'ru' => 'Навои']],
      ['id' => 55, 'region_id' => 6, 'title' => ['uz' => 'Nurota', 'ru' => 'Нурата']],
      ['id' => 56, 'region_id' => 6, 'title' => ['uz' => 'Uchquduq', 'ru' => 'Учкудук']],
      ['id' => 57, 'region_id' => 6, 'title' => ['uz' => 'Zarafshon', 'ru' => 'Зарафшан']],
      ['id' => 58, 'region_id' => 7, 'title' => ['uz' => 'Chortoq', 'ru' => 'Чартак']],
      ['id' => 59, 'region_id' => 7, 'title' => ['uz' => 'Chust', 'ru' => 'Чуст']],
      ['id' => 60, 'region_id' => 7, 'title' => ['uz' => 'Haqqulobod', 'ru' => 'Хакулабад']],
      ['id' => 61, 'region_id' => 7, 'title' => ['uz' => 'Namangan', 'ru' => 'Наманган']],
      ['id' => 62, 'region_id' => 7, 'title' => ['uz' => 'Pop', 'ru' => 'Пап']],
      ['id' => 63, 'region_id' => 7, 'title' => ['uz' => 'Toʻraqoʻrgʻon', 'ru' => 'Туракурган']],
      ['id' => 64, 'region_id' => 7, 'title' => ['uz' => 'Uchqo\'rg\'on', 'ru' => 'Учкурган']],
      ['id' => 65, 'region_id' => 8, 'title' => ['uz' => 'Oqtosh', 'ru' => 'Акташ']],
      ['id' => 66, 'region_id' => 8, 'title' => ['uz' => 'Bulung\'ur', 'ru' => 'Булунгур']],
      ['id' => 67, 'region_id' => 8, 'title' => ['uz' => 'Chelak', 'ru' => 'Чилек']],
      ['id' => 68, 'region_id' => 8, 'title' => ['uz' => 'Jomboy', 'ru' => 'Джамбай']],
      ['id' => 69, 'region_id' => 8, 'title' => ['uz' => 'Juma', 'ru' => 'Джума']],
      ['id' => 70, 'region_id' => 8, 'title' => ['uz' => 'Ishtixon', 'ru' => 'Иштыхан']],
      ['id' => 71, 'region_id' => 8, 'title' => ['uz' => 'Kattaqo\'rg\'on', 'ru' => 'Каттакурган']],
      ['id' => 72, 'region_id' => 8, 'title' => ['uz' => 'Nurobod', 'ru' => 'Нурабад']],
      ['id' => 73, 'region_id' => 8, 'title' => ['uz' => 'Samarqand', 'ru' => 'Самарканд']],
      ['id' => 74, 'region_id' => 8, 'title' => ['uz' => 'Urgut', 'ru' => 'Ургут']],
      ['id' => 75, 'region_id' => 8, 'title' => ['uz' => 'Ziyovuddin', 'ru' => 'Зиадин']],
      ['id' => 76, 'region_id' => 9, 'title' => ['uz' => 'Boysun', 'ru' => 'Байсун']],
      ['id' => 77, 'region_id' => 9, 'title' => ['uz' => 'Denov', 'ru' => 'Денау']],
      ['id' => 78, 'region_id' => 9, 'title' => ['uz' => 'Jarqo\'rg\'on', 'ru' => 'Джакурган']],
      ['id' => 79, 'region_id' => 9, 'title' => ['uz' => 'Qiziriq', 'ru' => 'Кизирик']],
      ['id' => 80, 'region_id' => 9, 'title' => ['uz' => 'Qumqo\'rg\'on', 'ru' => 'Кумкурган']],
      ['id' => 81, 'region_id' => 9, 'title' => ['uz' => 'Muzrabod', 'ru' => 'Музрабад']],
      ['id' => 82, 'region_id' => 9, 'title' => ['uz' => 'Sharg`un', 'ru' => 'Шаргунь']],
      ['id' => 83, 'region_id' => 9, 'title' => ['uz' => 'Sherobod', 'ru' => 'Шерабад']],
      ['id' => 84, 'region_id' => 9, 'title' => ['uz' => 'Sho\'rchi', 'ru' => 'Шурчи']],
      ['id' => 85, 'region_id' => 9, 'title' => ['uz' => 'Termiz', 'ru' => 'Термез']],
      ['id' => 86, 'region_id' => 10, 'title' => ['uz' => 'Baxt', 'ru' => 'Бахт']],
      ['id' => 87, 'region_id' => 10, 'title' => ['uz' => 'Guliston', 'ru' => 'Гулистан']],
      ['id' => 88, 'region_id' => 10, 'title' => ['uz' => 'Shirin', 'ru' => 'Ширин']],
      ['id' => 89, 'region_id' => 10, 'title' => ['uz' => 'Sirdaryo', 'ru' => 'Сырдарья']],
      ['id' => 90, 'region_id' => 10, 'title' => ['uz' => 'Yangiyer', 'ru' => 'Янгиер']],
      ['id' => 91, 'region_id' => 11, 'title' => ['uz' => 'Ohangaron', 'ru' => 'Ахангаран']],
      ['id' => 92, 'region_id' => 11, 'title' => ['uz' => 'Oqqo\'rg\'on', 'ru' => 'Аккурган']],
      ['id' => 93, 'region_id' => 11, 'title' => ['uz' => 'Olmaliq', 'ru' => 'Алмалык']],
      ['id' => 94, 'region_id' => 11, 'title' => ['uz' => 'Angren', 'ru' => 'Ангрен']],
      ['id' => 95, 'region_id' => 11, 'title' => ['uz' => 'Bekabad', 'ru' => 'Бекабад']],
      ['id' => 96, 'region_id' => 11, 'title' => ['uz' => 'Bo\'ka', 'ru' => 'Бука']],
      ['id' => 97, 'region_id' => 11, 'title' => ['uz' => 'Chinoz', 'ru' => 'Чиназ']],
      ['id' => 98, 'region_id' => 11, 'title' => ['uz' => 'Chirchiq', 'ru' => 'Чирчик']],
      ['id' => 99, 'region_id' => 11, 'title' => ['uz' => 'Do\'stobod', 'ru' => 'Дустабад']],
      ['id' => 100, 'region_id' => 11, 'title' => ['uz' => 'Eshonguzar', 'ru' => 'Эшангузар']],
      ['id' => 101, 'region_id' => 11, 'title' => ['uz' => 'G\'azalkent', 'ru' => 'Газалкент']],
      ['id' => 102, 'region_id' => 11, 'title' => ['uz' => 'Gulbahor', 'ru' => 'Гульбахор']],
      ['id' => 103, 'region_id' => 11, 'title' => ['uz' => 'Keles', 'ru' => 'Келес']],
      ['id' => 104, 'region_id' => 11, 'title' => ['uz' => 'Qibray', 'ru' => 'Кибрай']],
      ['id' => 105, 'region_id' => 11, 'title' => ['uz' => 'Krasnogorsk', 'ru' => 'Красногорск']],
      ['id' => 106, 'region_id' => 11, 'title' => ['uz' => 'Parkent', 'ru' => 'Паркент']],
      ['id' => 107, 'region_id' => 11, 'title' => ['uz' => 'Piskent', 'ru' => 'Пскент']],
      ['id' => 108, 'region_id' => 11, 'title' => ['uz' => 'Toshkent', 'ru' => 'Ташкент']],
      ['id' => 109, 'region_id' => 11, 'title' => ['uz' => 'Toʻytepa', 'ru' => 'Тойтепа']],
      ['id' => 110, 'region_id' => 11, 'title' => ['uz' => 'Yangibozor', 'ru' => 'Янгибазар']],
      ['id' => 111, 'region_id' => 11, 'title' => ['uz' => 'Yangiyo\'l', 'ru' => 'Янгиюль']],
      ['id' => 112, 'region_id' => 11, 'title' => ['uz' => 'Zafar', 'ru' => 'Зафар']],
      ['id' => 113, 'region_id' => 12, 'title' => ['uz' => 'Beshariq', 'ru' => 'Бешарык']],
      ['id' => 114, 'region_id' => 12, 'title' => ['uz' => 'Farg\'ona', 'ru' => 'Фергана']],
      ['id' => 115, 'region_id' => 12, 'title' => ['uz' => 'Qo\'qon', 'ru' => 'Коканд']],
      ['id' => 116, 'region_id' => 12, 'title' => ['uz' => 'Quva', 'ru' => 'Кува']],
      ['id' => 117, 'region_id' => 12, 'title' => ['uz' => 'Quvasoy', 'ru' => 'Кувасай']],
      ['id' => 118, 'region_id' => 12, 'title' => ['uz' => 'Marg\'ilon', 'ru' => 'Маргилан']],
      ['id' => 119, 'region_id' => 12, 'title' => ['uz' => 'Rishton', 'ru' => 'Риштан']],
      ['id' => 120, 'region_id' => 12, 'title' => ['uz' => 'Tinchlik', 'ru' => 'Хамза']],
      ['id' => 121, 'region_id' => 13, 'title' => ['uz' => 'Bog\'ot', 'ru' => 'Багат']],
      ['id' => 122, 'region_id' => 13, 'title' => ['uz' => 'Gurlan', 'ru' => 'Гурлен']],
      ['id' => 123, 'region_id' => 13, 'title' => ['uz' => 'Pitnak', 'ru' => 'Питнак']],
      ['id' => 124, 'region_id' => 13, 'title' => ['uz' => 'Urganch', 'ru' => 'Ургенч']],
      ['id' => 125, 'region_id' => 13, 'title' => ['uz' => 'Xonqa', 'ru' => 'Ханка']],
      ['id' => 126, 'region_id' => 13, 'title' => ['uz' => 'Xiva', 'ru' => 'Хива']],
    ];

    foreach ($cities as $city) {
      $city['title'] = json_encode($city['title'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
      \App\Models\City::query()->upsert($city, 'id');
    }
  }
}
